In [4]:
import time
import numpy as np

In [5]:
G = np.random.randint(20, size=(100,100))
H = np.random.randint(20, size=(100,100))
a = len(G)
d = int(a/2)
row_factor=np.zeros(a)
column_factor = np.zeros(a)
R = np.zeros((a,a))
my_start_time = time.time()
#Custom multiplication
for i in range(a):
    row_factor[i] = G[i][0] * G[i][1]
    for j in range(1, d):
        row_factor[i] += G[i][2*j - 1] * G[i][2*j]
for i in range(a):
    column_factor[i] = H[0][i] * H[1][i]
    for j in range(1,d):
        column_factor[i] += H[2*j - 1][i] * H[2*j][i]
for i in range(a):
    for j in range(a):
        R[i][j] = -(row_factor[i] + column_factor[j])
        for k in range(d):
            R[i][j] += (G[i][2*k-1]+H[2*k][j])*(G[i][2*k] + H[2*k-1][j])            
if (2 * (a/2)!= a):
    for i in range(a):
        for j in range(a):
            R[i][j] += G[i][b] * H[b][j]
print("--- %s seconds ---" % (time.time() - my_start_time))
dot_start_time = time.time()
#numpy multiplication
RR = np.dot(G,H)
print("--- %s seconds ---" % (time.time() - dot_start_time))

print(G)
print(H)
print(R)

--- 0.944941520690918 seconds ---
--- 0.0 seconds ---
[[ 5  8 11 ... 14  6 11]
 [ 9  0  9 ... 11 19  8]
 [17  2 17 ...  9  5  4]
 ...
 [16  3  7 ... 12  4 14]
 [ 6  0 17 ...  1 12 11]
 [16  4 10 ...  5  5 11]]
[[19  4 14 ... 12 17  5]
 [ 8  2 17 ... 19  6 10]
 [16 18  3 ...  2  4 10]
 ...
 [10 11  4 ...  2 14 19]
 [13  7 17 ... 17 19  5]
 [17 16  3 ...  7  5 16]]
[[ 9900.  9454.  8472. ...  8815.  9395.  8679.]
 [ 8913.  7967.  6623. ...  7212.  7748.  7131.]
 [ 9971.  9067.  8028. ...  8392.  9221.  8309.]
 ...
 [ 9984.  8973.  8334. ...  8252.  8852.  8355.]
 [ 9800.  9418.  8846. ...  8700.  8846.  8430.]
 [10124.  8799.  7571. ...  8681.  9016.  7807.]]
